version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: laravel_module_all
    restart: unless-stopped
    working_dir: /var/www/html
    # command: composer run devd
    volumes:
      - .:/var/www/html
      - ./docker/000-default.local.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "32126:80"
