version: '3.8'

name: cdapi-prod

services:
  app:
    container_name: cd_api
    image: ghbbb.xiaobei.fun/dongasai/cd_api:latest
    restart: unless-stopped
    # command: composer run devd
    volumes:
      - ./laravel/.env:/www/var/html/.env
      - ./laravel/storage:/www/var/html/storage/
    ports:
      - "32127:80"
