version: '3.8'

name: cdapi-prod

services:
  app:
    container_name: cd_api_prod
    # ghbbb 是 ghcr.io 的镜像
    image: ghcr.io/dongasai/cd_api:latest
    restart: unless-stopped
    # command: composer run devd
    volumes:
      - ./laravel/.env.production:/var/www/html/.env
      - ./laravel/storage:/var/www/html/storage/
    ports:
      - "32127:80"
